DEEPSORT:
  REID_CKPT: "weights/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.3
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 3
  N_INIT: 3
  NN_BUDGET: 100
  
YOLO:
  YOLO_WEIGHTS: "weights/yolov5s.pt"
  IMG_SIZE: 640
  CONF_THRES: 0.5
  IOU_THRES: 0.3

WATCH_BOX: [[100, 500, 1500, 700]]